CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    telefono VARCHAR(20),
    rol VARCHAR(20) NOT NULL DEFAULT 'cliente' CHECK (rol IN ('cliente', 'agente', 'administrador')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agentes (
    id_agente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE REFERENCES usuarios(id_usuario) ON DELETE RESTRICT ON UPDATE CASCADE,
    numero_licencia VARCHAR(100),
    fecha_ingreso DATE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS propietarios (
    id_propietario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    correo VARCHAR(150),
    direccion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS direcciones (
    id_direccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle VARCHAR(150) NOT NULL,
    numero VARCHAR(20),
    colonia VARCHAR(100),
    ciudad VARCHAR(100) NOT NULL,
    estado VARCHAR(100) NOT NULL,
    codigo_postal VARCHAR(10),
    pais VARCHAR(100) NOT NULL DEFAULT 'Mexico'
);

CREATE TABLE IF NOT EXISTS propiedades (
    id_propiedad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propietario INTEGER NOT NULL REFERENCES propietarios(id_propietario) ON DELETE RESTRICT,
    id_agente INTEGER REFERENCES agentes(id_agente) ON DELETE SET NULL,
    id_direccion INTEGER NOT NULL REFERENCES direcciones(id_direccion) ON DELETE RESTRICT,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('CASA', 'DEPARTAMENTO', 'TERRENO', 'LOCAL', 'OFICINA', 'EDIFICIO')),
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(15, 2) NOT NULL CHECK (precio > 0),
    operacion VARCHAR(10) NOT NULL CHECK (operacion IN ('VENTA', 'RENTA')),
    superficie NUMERIC(10, 2),
    habitaciones INTEGER NOT NULL DEFAULT 0,
    banos INTEGER NOT NULL DEFAULT 0,
    estacionamientos INTEGER NOT NULL DEFAULT 0,
    estado VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE' CHECK (estado IN ('DISPONIBLE', 'RESERVADA', 'VENDIDA', 'RENTADA', 'INACTIVA')),
    fecha_publicacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_propiedades_estado ON propiedades(estado);
CREATE INDEX IF NOT EXISTS idx_propiedades_tipo ON propiedades(tipo);
CREATE INDEX IF NOT EXISTS idx_propiedades_operacion ON propiedades(operacion);
CREATE INDEX IF NOT EXISTS idx_propiedades_precio ON propiedades(precio);

CREATE TABLE IF NOT EXISTS compras (
    id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_propiedad INTEGER NOT NULL
        REFERENCES propiedades(id_propiedad)
        ON DELETE RESTRICT,

    id_vendedor INTEGER NOT NULL
        REFERENCES propietarios(id_propietario)
        ON DELETE RESTRICT,

    id_agente INTEGER
        REFERENCES agentes(id_agente)
        ON DELETE SET NULL,

    precio_compra NUMERIC(15, 2) NOT NULL
        CHECK (precio_compra > 0),

    fecha_compra DATE NOT NULL DEFAULT CURRENT_DATE,

    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN (
            'PENDIENTE',
            'COMPLETADA',
            'CANCELADA'
        )),

    forma_pago VARCHAR(30),
    observaciones TEXT,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_compras_propiedad
ON compras(id_propiedad);

CREATE INDEX IF NOT EXISTS idx_compras_vendedor
ON compras(id_vendedor);

CREATE INDEX IF NOT EXISTS idx_compras_estado
ON compras(estado);

CREATE TABLE IF NOT EXISTS operaciones (
    id_operacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propiedad INTEGER NOT NULL REFERENCES propiedades(id_propiedad),
    id_comprador INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    id_agente INTEGER REFERENCES agentes(id_agente),
    tipo_operacion VARCHAR(10) NOT NULL
        CHECK (tipo_operacion IN ('VENTA', 'RENTA')),
    precio_acordado NUMERIC(15, 2) NOT NULL
        CHECK (precio_acordado > 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'INICIADA'
        CHECK (estado IN (
            'INICIADA',
            'NEGOCIACION',
            'RESERVADA',
            'CONTRATO_FIRMADO',
            'COMPLETADA',
            'CANCELADA'
        )),
    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMPTZ,
    observaciones TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS operacionp_por_propiedad
ON operaciones (id_propiedad)
WHERE estado IN (
    'INICIADA',
    'NEGOCIACION',
    'RESERVADA',
    'CONTRATO_FIRMADO'
);

-- Consulta opcional para verificar las tablas creadas:
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
-- ORDER BY table_name;
