ALTER TABLE IF EXISTS public.expedientes_legales
  ADD COLUMN IF NOT EXISTS contenido BYTEA,
  ADD COLUMN IF NOT EXISTS mime_type VARCHAR(150),
  ADD COLUMN IF NOT EXISTS tamano_bytes BIGINT,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS public.coincidencias (
  id_coincidencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_lead BIGINT NOT NULL REFERENCES public.leads(id_lead) ON DELETE CASCADE,
  id_propiedad INTEGER NOT NULL REFERENCES public.propiedades(id_propiedad) ON DELETE CASCADE,
  puntuacion NUMERIC(5, 2) NOT NULL CHECK (puntuacion >= 0 AND puntuacion <= 100),
  creada_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (id_lead, id_propiedad)
);

CREATE INDEX IF NOT EXISTS idx_coincidencias_lead ON public.coincidencias(id_lead);
CREATE INDEX IF NOT EXISTS idx_expedientes_propiedad ON public.expedientes_legales(id_propiedad);
