BEGIN;

ALTER TABLE public.propiedades
  ADD COLUMN IF NOT EXISTS latitud NUMERIC(10, 7),
  ADD COLUMN IF NOT EXISTS longitud NUMERIC(10, 7);

CREATE TABLE IF NOT EXISTS public.contratos (
  id_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_operacion VARCHAR(10) NOT NULL CHECK (tipo_operacion IN ('VENTA', 'RENTA')),
  id_cliente INTEGER NOT NULL REFERENCES public.clientes(id_cliente) ON DELETE RESTRICT,
  id_propiedad INTEGER NOT NULL REFERENCES public.propiedades(id_propiedad) ON DELETE RESTRICT,
  id_vendedor INTEGER NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE RESTRICT,
  fecha_contrato DATE NOT NULL DEFAULT CURRENT_DATE,
  precio_total NUMERIC(15, 2) NOT NULL CHECK (precio_total > 0),
  renta_mensual NUMERIC(15, 2) CHECK (renta_mensual IS NULL OR renta_mensual > 0),
  fecha_inicio DATE,
  fecha_fin DATE,
  frente_metros NUMERIC(10, 2) NOT NULL CHECK (frente_metros > 0),
  fondo_metros NUMERIC(10, 2) NOT NULL CHECK (fondo_metros > 0),
  superficie_m2 NUMERIC(12, 2) NOT NULL CHECK (superficie_m2 > 0),
  latitud NUMERIC(10, 7),
  longitud NUMERIC(10, 7),
  nombre_cliente VARCHAR(200) NOT NULL,
  correo_cliente VARCHAR(150) NOT NULL,
  telefono_cliente VARCHAR(30),
  curp_cliente VARCHAR(30),
  nombre_vendedor VARCHAR(200) NOT NULL,
  correo_vendedor VARCHAR(150) NOT NULL,
  titulo_propiedad VARCHAR(200) NOT NULL,
  calle VARCHAR(150) NOT NULL,
  numero VARCHAR(30),
  colonia VARCHAR(100),
  ciudad VARCHAR(100) NOT NULL,
  estado VARCHAR(100) NOT NULL,
  codigo_postal VARCHAR(10),
  observaciones TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contratos_coordenadas_completas CHECK (
    (latitud IS NULL AND longitud IS NULL)
    OR (latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180)
  ),
  CONSTRAINT contratos_coordenadas_venta CHECK (
    tipo_operacion <> 'VENTA' OR (latitud IS NOT NULL AND longitud IS NOT NULL)
  ),
  CONSTRAINT contratos_fechas_renta CHECK (
    tipo_operacion <> 'RENTA'
    OR (fecha_inicio IS NOT NULL AND (fecha_fin IS NULL OR fecha_fin >= fecha_inicio))
  )
);

CREATE INDEX IF NOT EXISTS idx_contratos_vendedor
  ON public.contratos(id_vendedor, creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_contratos_cliente
  ON public.contratos(id_cliente, creado_en DESC);

CREATE OR REPLACE FUNCTION public.registrar_auditoria()
RETURNS TRIGGER AS $$
DECLARE
  usuario_actual INTEGER;
  fila_anterior JSONB;
  fila_nueva JSONB;
  fila_actual JSONB;
  entidad_id_value TEXT;
  auditoria_tiene_detalle BOOLEAN;
BEGIN
  usuario_actual := NULLIF(current_setting('app.user_id', true), '')::INTEGER;
  fila_anterior := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END;
  fila_nueva := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END;
  fila_actual := COALESCE(fila_nueva, fila_anterior);
  entidad_id_value := COALESCE(
    fila_actual ->> 'id_usuario',
    fila_actual ->> 'id_cliente',
    fila_actual ->> 'id_propiedad',
    fila_actual ->> 'id_contrato',
    fila_actual ->> 'id_venta',
    fila_actual ->> 'id_renta',
    fila_actual ->> 'id_lead',
    fila_actual ->> 'id_cita',
    fila_actual ->> 'id_oferta',
    fila_actual ->> 'id_documento',
    fila_actual ->> 'id_comision',
    fila_actual ->> 'id_pago'
  );

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'auditoria' AND column_name = 'detalle'
  ) INTO auditoria_tiene_detalle;

  IF auditoria_tiene_detalle THEN
    EXECUTE 'INSERT INTO public.auditoria (id_usuario, accion, entidad, entidad_id, detalle)
      VALUES ($1, $2, $3, $4, $5)'
      USING usuario_actual, TG_OP, TG_TABLE_NAME, entidad_id_value,
        jsonb_build_object('anterior', fila_anterior, 'nuevo', fila_nueva);
  ELSE
    EXECUTE 'INSERT INTO public.auditoria
      (id_usuario, accion, entidad, entidad_id, datos_anteriores, datos_nuevos)
      VALUES ($1, $2, $3, $4, $5, $6)'
      USING usuario_actual, TG_OP, TG_TABLE_NAME, entidad_id_value, fila_anterior, fila_nueva;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMIT;
